services: 
  db: 
    image: postgres
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - 'redis'
      
  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - 'redis/data'
  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3